version: '3.9'
name: "gpx_routes_backend"

services:
  server:
    extends:
      file: docker-compose.base.yml
      service: server-local

  database:
    extends:
      file: docker-compose.base.yml
      service: database

volumes:
  database:
